### ISSUE TITLE
[RFC] Merging support for `wasmedge` into upstream.

### ISSUE THREAD

**Issue by flouthoc** [second-state/crunw#6]
Hi Team,

I was recently working with adding support for `wasmer` into upstream `crun`. I think it would be great if we could also get support for `wasmedge` into upstream `crun`.

If you are interested, we will be happy to accept this feature upstream and help with the maintenance.  Another advantage is that crun is already present on many distros, and as soon as the required libraries are present, we can enable wasm support by default

Thanks

**Comment by hydai** [comment]
Awesome! We would love to contribute to upstream. Is there anything we need to know or follow before we send a pull request? For example, should we open an issue and discuss with this feature first?

**Comment by flouthoc** [comment]
@hydai I don't think any issue is needed so please feel free to open a pull request on upstream. :). There is already `wasmer_do_exec` support added to upstream so i guess it should be easy to add.  But if you feel something needs to be discussed please open issue on upstream.

**Comment by giuseppe** [comment]
do we need to make the two wasm libraries mutually exclusive?  Or how would we handle the `module.wasm.image/variant=compat` annotation?

**Comment by flouthoc** [comment]
Could there be any possibility of adding another annotation `module.wasm.image/runtime=<wasmer/wasmedge>` and if runtime not specified it falls-back to default one. I am inclined to have `wasmer` as default but dont have a strict choice.

**Comment by giuseppe** [comment]
should the issue be closed since the support was merged into upstream crun?
